### ISSUE TITLE
Yarn run dev Failed

### ISSUE THREAD

**Issue by Insidebox** [infernojs/inferno-website#89]
Hello I am trying to install inferno but I got with v7.10.1 OS X NVM

`ERROR in ./src/assets/css/index.scss
Module build failed: ModuleBuildError: Module build failed: 
@import "../../../../node_modules/bootstrap/scss/normalize";

      File to import not found or unreadable: ../../../../node_modules/bootstrap/scss/normalize.
Parent style sheet: /Users/insidebox/Documents/GitHub/inferno-website/src/assets/css/modules/_common.scss
      in /Users/insidebox/Documents/GitHub/inferno-website/src/assets/css/modules/_common.scss (line 1, column 1)
    at runLoaders (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/webpack/lib/NormalModule.js:194:19)
    at /Users/insidebox/Documents/GitHub/inferno-website/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/insidebox/Documents/GitHub/inferno-website/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/async/dist/async.js:2244:31)
    at Object.callback (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/async/dist/async.js:906:16)
    at options.error (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/node-sass/lib/index.js:294:32)
 @ ./src/client.js 9:0-34
 @ multi webpack-dev-server/client?http://localhost:8082 webpack/hot/only-dev-server ./core/polyfills.js ./src/client.js

ERROR in ./src/assets/css/index.scss
Module build failed: ModuleBuildError: Module build failed: 
@import "../../../../node_modules/bootstrap/scss/normalize";
^
      File to import not found or unreadable: ../../../../node_modules/bootstrap/scss/normalize.
Parent style sheet: /Users/insidebox/Documents/GitHub/inferno-website/src/assets/css/modules/_common.scss
      in /Users/insidebox/Documents/GitHub/inferno-website/src/assets/css/modules/_common.scss (line 1, column 1)
    at runLoaders (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/webpack/lib/NormalModule.js:194:19)
    at /Users/insidebox/Documents/GitHub/inferno-website/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/insidebox/Documents/GitHub/inferno-website/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/async/dist/async.js:2244:31)
    at Object.callback (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/async/dist/async.js:906:16)
    at options.error (/Users/insidebox/Documents/GitHub/inferno-website/node_modules/node-sass/lib/index.js:294:32)`

And with the latest LTS
`yarn install v0.27.5
warning ../../../package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error koa-mount@3.0.0: The engine "node" is incompatible with this module. Expected version ">= 7.6.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

Thanks

**Comment by Havunen** [comment]
Can you try with native  "npm install" - "npm run dev" "npm run prod" procedure please.

**Comment by Insidebox** [comment]
v7.10.1 OS X

`inferno-website-master insidebox$ npm install
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g`

`inferno-website-master insidebox$ npm run dev

> inferno-website@1.0.0 dev /Users/insidebox/Desktop/inferno-website-master
> cross-env NODE_ENV=development nodemon index.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: src/client/components/App /Users/insidebox/Desktop/inferno-website-master/src/server/**/* src/shared index.js /Users/insidebox/Desktop/inferno-website-master/core/**/*
[nodemon] starting `node index.js`
  inferno:warn clean-webpack-plugin: /Users/insidebox/Desktop/inferno-website-master/build has been removed. +0ms
  inferno:warn clean-webpack-plugin: /Users/insidebox/Desktop/inferno-website-master/public has been removed. +5ms
  inferno:static /Users/insidebox/Desktop/inferno-website-master/public +3s
  inferno:static /Users/insidebox/Desktop/inferno-website-master/public/build +1ms
  inferno:static /Users/insidebox/Desktop/inferno-website-master/public/assets +0ms
  inferno:static /Users/insidebox/Desktop/inferno-website-master/public/docs +0ms
  inferno:start Listening on port 8080 +252ms
  webpack:compiler Running on port 8082 +1ms
        Asset     Size  Chunks  Chunk Names
         0.js  18.3 kB       0  
    bundle.js   763 kB       1  bundle
     react.js  52.3 kB       2  react
     0.js.map  35.4 kB       0  
bundle.js.map   831 kB       1  bundle
 react.js.map  73.2 kB       2  react

ERROR in ./src/assets/css/index.scss
Module build failed: ModuleBuildError: Module build failed: 
@import "../../../../node_modules/bootstrap/scss/normalize";
^
      File to import not found or unreadable: ../../../../node_modules/bootstrap/scss/normalize.
Parent style sheet: /Users/insidebox/Desktop/inferno-website-master/src/assets/css/modules/_common.scss
      in /Users/insidebox/Desktop/inferno-website-master/src/assets/css/modules/_common.scss (line 1, column 1)
    at runLoaders (/Users/insidebox/Desktop/inferno-website-master/node_modules/webpack/lib/NormalModule.js:194:19)
    at /Users/insidebox/Desktop/inferno-website-master/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/insidebox/Desktop/inferno-website-master/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/insidebox/Desktop/inferno-website-master/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/insidebox/Desktop/inferno-website-master/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/Users/insidebox/Desktop/inferno-website-master/node_modules/async/dist/async.js:2244:31)
    at Object.callback (/Users/insidebox/Desktop/inferno-website-master/node_modules/async/dist/async.js:906:16)
    at options.error (/Users/insidebox/Desktop/inferno-website-master/node_modules/node-sass/lib/index.js:294:32)
 @ ./src/client.js 9:0-34
 @ multi webpack-dev-server/client?http://localhost:8082 webpack/hot/only-dev-server ./core/polyfills.js ./src/client.js

ERROR in ./src/assets/css/index.scss
Module build failed: ModuleBuildError: Module build failed: 
@import "../../../../node_modules/bootstrap/scss/normalize";
^
      File to import not found or unreadable: ../../../../node_modules/bootstrap/scss/normalize.
Parent style sheet: /Users/insidebox/Desktop/inferno-website-master/src/assets/css/modules/_common.scss
      in /Users/insidebox/Desktop/inferno-website-master/src/assets/css/modules/_common.scss (line 1, column 1)
    at runLoaders (/Users/insidebox/Desktop/inferno-website-master/node_modules/webpack/lib/NormalModule.js:194:19)
    at /Users/insidebox/Desktop/inferno-website-master/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/insidebox/Desktop/inferno-website-master/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/insidebox/Desktop/inferno-website-master/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/insidebox/Desktop/inferno-website-master/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/Users/insidebox/Desktop/inferno-website-master/node_modules/async/dist/async.js:2244:31)
    at Object.callback (/Users/insidebox/Desktop/inferno-website-master/node_modules/async/dist/async.js:906:16)
    at options.error (/Users/insidebox/Desktop/inferno-website-master/node_modules/node-sass/lib/index.js:294:32)
webpack: Failed to compile.
`

**Comment by Insidebox** [comment]
Now using node v6.11.2 (npm v3.10.10)

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: src/client/components/App /Users/insidebox/Desktop/inferno-website-master/src/server/**/* src/shared index.js /Users/insidebox/Desktop/inferno-website-master/core/**/*
[nodemon] starting `node index.js`
  inferno:warn clean-webpack-plugin: /Users/insidebox/Desktop/inferno-website-master/build has been removed. +0ms
  inferno:warn clean-webpack-plugin: /Users/insidebox/Desktop/inferno-website-master/public has been removed. +13ms
/Users/insidebox/Desktop/inferno-website-master/node_modules/koa-mount/index.js:48
  return async function (ctx, upstream){
               ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/insidebox/Desktop/inferno-website-master/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/insidebox/Desktop/inferno-website-master/src/server/server.js:8:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/insidebox/Desktop/inferno-website-master/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/insidebox/Desktop/inferno-website-master/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Havunen** [comment]
Some dependency seems to have broken it. I can look into this.

**Comment by Havunen** [comment]
Ok, fixed

**Comment by Insidebox** [comment]
Thanks I try
